package com.tech.givvruk.utils;

public class Project {
	
	private String PROJECTNAME ;
	private String PROJECTGOAL;
	private String PROJECTTAG ;
	private String PROJECTRAISED ;
	private String PROJECTDESCRIPTION ;
	private String PROJECTSMALLIMG ;
	private String PROJECTLARGEIMG ;
	private String PROJECTID ;
	private String CHARITYID ;
	private String PROJECTLENGTH ;
	private String PROJECTCREATEDAT ;
	private String PROJECTCOLORCODE ;
	private String PROJECTDAYSLEFT ;
	private String PROJECTSUPPORTERS;
	
	public Project(String pROJECTNAME, String pROJECTGOAL, String pROJECTTAG,
			String pROJECTRAISED, String pROJECTDESCRIPTION,
			String pROJECTSMALLIMG, String pROJECTLARGEIMG, String pROJECTID,
			String cHARITYID,String pROJECTLENGTH,String pROJECTCREATEDAT,String pROJECTCOLORCODE,String pROJECTDAYSLEFT,String pROJECTSUPPORTERS) {
		super();
		PROJECTNAME = pROJECTNAME;
		PROJECTGOAL = pROJECTGOAL;
		PROJECTTAG = pROJECTTAG;
		PROJECTRAISED = pROJECTRAISED;
		PROJECTDESCRIPTION = pROJECTDESCRIPTION;
		PROJECTSMALLIMG = pROJECTSMALLIMG;
		PROJECTLARGEIMG = pROJECTLARGEIMG;
		PROJECTID = pROJECTID;
		CHARITYID = cHARITYID;
		PROJECTLENGTH = pROJECTLENGTH;
		PROJECTCREATEDAT = pROJECTCREATEDAT;
		PROJECTCOLORCODE = pROJECTCOLORCODE;
		PROJECTDAYSLEFT = pROJECTDAYSLEFT;
		PROJECTSUPPORTERS = pROJECTSUPPORTERS;
	}
	
	public String getPROJECTSUPPORTERS() {
		return PROJECTSUPPORTERS;
	}

	public void setPROJECTSUPPORTERS(String pROJECTSUPPORTERS) {
		PROJECTSUPPORTERS = pROJECTSUPPORTERS;
	}

	public String getPROJECTDAYSLEFT() {
		return PROJECTDAYSLEFT;
	}

	public void setPROJECTDAYSLEFT(String pROJECTDAYSLEFT) {
		PROJECTDAYSLEFT = pROJECTDAYSLEFT;
	}

	public String getPROJECTCOLORCODE() {
		return PROJECTCOLORCODE;
	}
	public void setPROJECTCOLORCODE(String pROJECTCOLORCODE) {
		PROJECTCOLORCODE = pROJECTCOLORCODE;
	}
	public String getPROJECTLENGTH() {
		return PROJECTLENGTH;
	}
	public void setPROJECTLENGTH(String pROJECTLENGTH) {
		PROJECTLENGTH = pROJECTLENGTH;
	}
	public String getPROJECTCREATEDAT() {
		return PROJECTCREATEDAT;
	}
	public void setPROJECTCREATEDAT(String pROJECTCREATEDAT) {
		PROJECTCREATEDAT = pROJECTCREATEDAT;
	}
	public String getPROJECTNAME() {
		return PROJECTNAME;
	}
	public void setPROJECTNAME(String pROJECTNAME) {
		PROJECTNAME = pROJECTNAME;
	}
	public String getPROJECTGOAL() {
		return PROJECTGOAL;
	}
	public void setPROJECTGOAL(String pROJECTGOAL) {
		PROJECTGOAL = pROJECTGOAL;
	}
	public String getPROJECTTAG() {
		return PROJECTTAG;
	}
	public void setPROJECTTAG(String pROJECTTAG) {
		PROJECTTAG = pROJECTTAG;
	}
	public String getPROJECTRAISED() {
		return PROJECTRAISED;
	}
	public void setPROJECTRAISED(String pROJECTRAISED) {
		PROJECTRAISED = pROJECTRAISED;
	}
	public String getPROJECTDESCRIPTION() {
		return PROJECTDESCRIPTION;
	}
	public void setPROJECTDESCRIPTION(String pROJECTDESCRIPTION) {
		PROJECTDESCRIPTION = pROJECTDESCRIPTION;
	}
	public String getPROJECTSMALLIMG() {
		return PROJECTSMALLIMG;
	}
	public void setPROJECTSMALLIMG(String pROJECTSMALLIMG) {
		PROJECTSMALLIMG = pROJECTSMALLIMG;
	}
	public String getPROJECTLARGEIMG() {
		return PROJECTLARGEIMG;
	}
	public void setPROJECTLARGEIMG(String pROJECTLARGEIMG) {
		PROJECTLARGEIMG = pROJECTLARGEIMG;
	}
	public String getPROJECTID() {
		return PROJECTID;
	}
	public void setPROJECTID(String pROJECTID) {
		PROJECTID = pROJECTID;
	}
	public String getCHARITYID() {
		return CHARITYID;
	}
	public void setCHARITYID(String cHARITYID) {
		CHARITYID = cHARITYID;
	}
	
	

}
